package ru.istok.backend.common.exception;

public enum ErrorCode {
    USER_NOT_FOUND,
    LOGIN_ALREADY_EXISTS,
    INVALID_LOGIN_OR_PASSWORD,
    USER_ARCHIVED,
    ACCESS_DENIED,
    VALIDATION_ERROR,
    COURSE_NOT_FOUND,
    LESSON_NOT_FOUND,
    LESSON_LOCKED,
    CONTENT_IMPORT_ERROR,
    SUBMIT_VALIDATION_ERROR
}
